### ISSUE TITLE
HR Zones and other QS tracking

### ISSUE THREAD

**Issue by JeffCdev** [jimmykane/quantified-self#197]
Hi Jimmy,
Thank you for creating an amazing piece of software!!! Just set it up in a VM, and I'm incredibly impressed with what it is capable of doing.  Couple of questions, first, I haven't been able to figure out how to display time in HR zones for an exercise.  I'm importing a TCX file, it that makes any difference. Second, I'm wondering if you have any plans to add other "QS" measures to your application.  For example, weight, BMI, blood pressure, etc.. I'm looking to a "single pane of glass" local only application for tracking fitness, and haven't been able to find one yet. Thanks again!!!

**Comment by jimmykane** [comment]
Hey thanks for the kind words.

Let me answer a few:

Tcx files do not contain zone info unfortunately. That is because they
cannot contain summary header information.

Regarding weight etc yes this is planned.

I am on a time off from programming due to personal reasons , mainly being
a new dad, but development will start again around end of this month.

**Comment by JeffCdev** [comment]
Congratulations on fatherhood!!! Enjoy your time with your child, and I look forward to seeing what you will add to your app when you decide to continue.
