### ISSUE TITLE
My Tracks: Allow for a longer date range

### ISSUE THREAD

**Issue by tuxella** [jimmykane/quantified-self#217]
Currently, we can choose between
- "This week"
- "Last 30 days"
- "This Month"
- "2020" (which I suppose means "this year")

I would like to be able to show the tracks for all the activities I have loaded into quantified-self, and maybe to be able to select a time range, like in the dashboard.

**Comment by jimmykane** [comment]
Hey hi @tuxella thanks for this issue :-) 

You are correct that 2020 essentially means this year. 

I ll be adding more options and perhaps the "all" option like i the dashboard. 

The only reason this is not done yet is because I wanted to monitor the performance on terms of costs. So far it looks quite ok, so I ll be adding more options. 

However, about the date range search, perhaps it will add too much stuff over the map. What do you think?

**Comment by tuxella** [comment]
An "all" option would be good for me.

I think that adding options would eventually result in a much more complicated tool (see for example the "Activities" tab in Veloviewer…)

Another useful option I would be to select a map theme, but I think it should use the map theme already chosen in the settings.

**Comment by jimmykane** [comment]
Should have the all option for now. 

Could you be so kind as to add a feature request for the theme ? 

The thing is that the Google maps themes can't apply to MyTracks , because it's made with leaflet for faster and opensource layers. There is a plethora of map tiles I can create themes and let the user choose but it has to be specific to this component.

**Comment by tuxella** [comment]
Thank you for the new "all" button. But it doesn't seem to have any effet on which tracks are loaded and displayed on the map :-(

I created an issue for the map theme selection: https://github.com/jimmykane/quantified-self/issues/218

**Comment by jimmykane** [comment]
hmmm. Are you sure? 

Could you describe the issue? It should load "all" as the dashboard does 

Some video / printscreens could help

**Comment by jimmykane** [comment]
Also logging out / in could as well

**Comment by jimmykane** [comment]
Ok I am suspecting something. 

2 Questions: 

- Have you edited the imported activities from Suunto app on QS? 
- When was it that you did the history import ?

**Comment by jimmykane** [comment]
I am sure I know the cause of the issue just trying to figure out a solution :-D

**Comment by tuxella** [comment]
I don't think I ever edited an activity on QS, but I'm not 100% sure either. But I have deleted in the Suunto App an activity that is in QS (one of these duplicates: https://quantified-self.io/user/xmqnMbs71TMJuFbdi5R4gRQfzrb2/event/3cPQA91MbTn2CvY9miDsisDtia35idMPKwfw3M3Vh5XSyqm or https://quantified-self.io/user/xmqnMbs71TMJuFbdi5R4gRQfzrb2/event/3cPQA91MbTn2CvY9jYcLyLr5bUqoENi4SRLLsmkZzjYC2ua )

Is the import date shown somewhere on QS?

**Comment by jimmykane** [comment]
2 options here. I think this issue is due to "old" import if you have done it like half a year ago. 

Some time ago on QS when the import happened it didn't crate start / end points for the activities. Thus those are considered indoors when "searching" 

Option 1: Delete your account on QS, create then again , import history etc. 
Option 2: Redo the history import BUT this might create duplicates. That is due to the "old import". 

If you have not edited stuff imo option 1 is the way to go and enjoy!

**Comment by tuxella** [comment]
Good, I'll go with the option 1 and let you know how it goes.

Thank you

**Comment by tuxella** [comment]
ok, after deleting my account, recreating it and re-importing my activities, this works 👍 

Thank you
